### ISSUE TITLE
add dir/glob support, file watching, auto-load for plugins

### ISSUE THREAD

**Issue by michael-ciniawsky** [GitScrum/posthtml-cli#36]
hey, are there any plans to support the following ?

*glob patterns*
 ```bash
posthtml -i *.html -o [name].html
```
*file watching*
```bash
posthtml -i  *.html -o [name].html  -w|--watch
``` 
*auto-load plugins* directly from pkg.json, like [posthtml-load-plugins](https://github.com/michael-ciniawsky/posthtml-load-plugins) and then specify the plugins options in the pkg.json as well
```bash
posthtml -i *.html -o [name].html -w (if  !-c|--config flag => auto-load plugins && options)
```
```json 
"dependencies": {
  "posthtml-bem":  "0.0.1"
},
posthtml: {
  "bem":  "options..."
}
```
Are PR's welcome to this project, i could implement this stuff if accepted?

**Comment by GitScrum** [comment]
Hi. 
_glob patterns_ is planned see [#9](https://github.com/GitScrum/posthtml-cli/issues/9)
_wathing files/dir_ nice idea, added in plan. Tanks !
_auto-load-plugins_ great pkg, but this implemented in the project, used default options yargs (read package.json or config path), but most likely will add to the core. Tanks !!!

**Comment by michael-ciniawsky** [comment]
hi ohh sry i missed this one [#9](https://github.com/GitScrum/posthtml-cli/issues/9) :).

argv.require as i saw in the cli module does nearly the same thing i intended to provide with the load-plugins pkg, maybe we could aline the behaviour of how it's done in some way?

I hack around with [glob](https://github.com/package/glob) and [watch](https://npmjs.org/package/watch)
glob works, watch seems to... tests leaking

If you want some help or assign one of the issues let me know otherwise looking forward to this improvements, especially for npm build tooling :).

**Comment by GitScrum** [comment]
Glob - 404 
Watch not best choice, i like [chokidar](https://github.com/paulmillr/chokidar)

> maybe we could aline the behaviour of how it's done in some way?

Sorry i'm not understand question.

**Comment by michael-ciniawsky** [comment]
sry... [glob](https://npmjs.org//package/glob)
that seems to be a better option, never heard of that :)

As i understand argv.require currently reads the plugins this way
 
```json
"posthtml": {
    "require": ["posthtml-custom-elements"]
  }
``` 
then maps them to the plugins array 

```js
var plugins = [];

if (argv.require) {
  plugins = argv.require.map(function (name) {
    return require(name)(argv[name]);
  });
}
```
while posthtml-load-plugins does it this way 

```json
"dependencies": {
  "posthtml-bem": "0.0.0"
},
"devDependencies": {
  "posthtml-exp": "0.0.0"
},
"posthtml": {
    "bem":  {"options..."},
    "exp":  {"options..."}
  }
```

```js
var pkg = require('./package.json')
var options = argv.require || {}

// Prototype for plugin before pushed to plugins array
  function Plugin (plugin, options) {
    function namespace (plugin) {
      let namespace = plugin
        .slice(9)
        .replace(/-(\w)/g, (match) => {
          return match.replace(/-/, '').toUpperCase()
        })
      return `${namespace}`
    }

    return {
      plugin: require(`${plugin}`),
      namespace: namespace(plugin),
      defaults: {}
    }
  }

// Filter for plugins in pkg.dependencies/devDependencies
  function isPlugin (element, index, array) {
    return element.match(/posthtml-[\w]/)
  }

 var plugins = []

// Build plugins array from dependencies/devDependencies
  Object.keys(pkg.dependencies).filter(isPlugin).forEach(plugin => {
    plugins.push(new Plugin(plugin))
  })

  Object.keys(pkg.devDependencies).filter(isPlugin).forEach(plugin => {
    plugins.push(new Plugin(plugin))
  })

  var processors = []

// Inject custom options foreach plugin or use defaults
  plugins.forEach(plugin => {
    var namespaceOptions = plugin.namespace in options ? options[plugin.namespace] : options
    var pluginOptions = {}

    Object.keys(plugin.defaults).forEach(key => {
      pluginOptions[key] = plugin.defaults[key]
    })

    Object.keys(namespaceOptions).forEach(key => {
      pluginOptions[key] = namespaceOptions[key]
    })

    if (namespaceOptions && !processorOptions.disable) {
      processor.push(plugins.plugin(pluginOptions))
    }
  })

  return processors
}
```
The "posthtml" option in pkg.json just contains the plugin options which then get injected later.

**Comment by GitScrum** [comment]
@michael-ciniawsky Thanks I saw it, that's cool, I've added it to the plan. It is planned to loader pkg option is the order of loading ?

**Comment by michael-ciniawsky** [comment]
not really..... currently just filters the include plugin to unshift it in the plugins array that's an serious issue to find a solution here for plugins requiring specific order.if you have a solution in mind please let me know :)

**Comment by GitScrum** [comment]
I think through the options or to draw up a minimum list yourself and Deposit to edit it. Until such ideas.

**Comment by GitScrum** [comment]
@michael-ciniawsky add support read/write and replace options
