### ISSUE TITLE
fixed coverage

### ISSUE THREAD

**Issue by GitScrum** [GitScrum/posthtml-cli#39]
Error: ENOENT: no such file or directory, scandir '/home/travis/build/GitScrum/posthtml-cli/.nyc_output'
If set nyc@6 before ava, tests down. If used nyc@5 work.
Waiting PR for [issue](https://github.com/yargs/yargs/issues/424)
[PR](https://github.com/yargs/yargs/pull/432)
Added tmp fix ```javascript delete require.cache[require.resolve('yargs')]```

**Comment by GitScrum** [comment]
Waiting fot [pr](https://github.com/yargs/yargs/issues/424)
Added tmp fix ```javascript delete require.cache[require.resolve('yargs')]```

**Comment by bcoe** [comment]
@GitScrum try:

`npm i nyc@next`

You can now run yargs in a non-singleton mode with `require('yargs/yargs')` it should fix your problem for you :+1:

**Comment by GitScrum** [comment]
@bcoe Tanks !
